version: "3.8"

services:
  storefront-dev:
    build:
      context: ./services/storefront-ui
    ports:
      - "5173:5173/tcp"
    volumes:
      - ./services/storefront-ui:/app
      - /app/node_modules
    command: "bun run dev -- --host 0.0.0.0"

  recommendation-api:
    build:
      context: ./services/recommendation-api
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped

  event-collector-api:
    build:
      context: ./services/event-collector-api
    ports:
      - "3000:3000/tcp"
    restart: unless-stopped

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181/tcp"

  kafka:
    image: docker.io/confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092/tcp"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jobmanager:
    build: ./services/profile-builder-processor
    ports:
      - "8081:8081" 
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build: ./services/profile-builder-processor
    depends_on:
      - jobmanager
      - kafka
    command: taskmanager 
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  