version: "3.8"

services:
  storefront:
    build:
      context: ./services/storefront-ui
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped