# === Build Stage ===
FROM docker.io/library/golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /server ./...

# === Final Stage ===
FROM docker.io/library/alpine:latest
COPY --from=builder /server /server
EXPOSE 8080
CMD [ "/server" ]